import "./globals.css";
import { Inter, Roboto } from "next/font/google";
import { Providers } from "@/components/Providers";
import { NavBar } from "@/components/NavBar";

const roboto = Roboto({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-screen max-w-full">
      <body className={`${roboto.className} h-full bg-secondary`}>
        <Providers>
          <NavBar />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
